### ISSUE TITLE
PVCA on continuous variables

### ISSUE THREAD

**Issue by royfrancis** [dleelab/pvca#1]
Hi,
Is it possible to run PVCA when batch variables are continuous rather than categorical? Or would that be same/similar to a normal PCA? Also, what if I have several variables and some are categorical and some continuous?
Thanks.

**Comment by dleelab** [comment]
Hi Roy,

PVCA models all variables as random effects so you should use only category
variables/factors as independent variables here. So you better convert the
continuous batch variables to categorical variables (maybe using 'cut'
function in R). Hope this is helpful for you and thank you for your
interest in the package.

Best,
Don

**Comment by royfrancis** [comment]
Ah ok. That was my solution anyway. I felt like my breaks in cut were just arbitrary and I am not sure how they would influence the PVCA results. Anyway, thanks for your reply.
